name: the_names_of
description: The names of Allah

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  path_provider: ^2.0.2
  sqflite: ^2.0.0+3
  flutter_html: ^2.1.0
  share_plus: ^2.0.4
  clipboard: ^0.1.3
  scrollable_positioned_list: ^0.2.0-nullsafety.0
  screenshot: ^1.2.3
  page_view_dot_indicator: ^1.0.0
  flip_card: ^0.5.0
  assets_audio_player: ^3.0.3+6
  flutter_zoom_drawer: ^2.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:

  uses-material-design: true

  assets:
  - assets/databases/
  - assets/audios/
  - assets/images/
  fonts:
    - family: Gilroy
      fonts:
        - asset: assets/fonts/gilroy_medium.ttf
    - family: Arabic
      fonts:
        - asset: assets/fonts/arabic.ttf