name: the_names_of
description: The names of Allah

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.3.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  path_provider: ^2.1.5
  path: ^1.9.0
  flutter_html: ^3.0.0-beta.2
  html: ^0.15.4
  sqflite: ^2.4.1
  share_plus: ^10.1.2
  screenshot: ^3.0.0
  clipboard: ^0.1.3
  scrollable_positioned_list: ^0.3.8
  just_audio: ^0.9.42
  hive_flutter: ^1.1.0
  flip_card: ^0.7.0
  smooth_page_indicator: ^1.2.0+3
  provider: ^6.1.2
  flutter_material_color_picker: ^1.2.0
  wakelock_plus: ^1.2.8
  intl: ^0.19.0
  timezone: ^0.10.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0

flutter:

  uses-material-design: true

  assets:
    - assets/databases/
    - assets/audios/
  fonts:
    - family: Gilroy
      fonts:
        - asset: assets/fonts/gilroy_medium.ttf
    - family: Montserrat
      fonts:
        - asset: assets/fonts/montserrat_medium.ttf
    - family: Raleway
      fonts:
        - asset: assets/fonts/raleway_regular.ttf
    - family: Scheherezade
      fonts:
        - asset: assets/fonts/scheh.ttf
